name: Dispatch button 
on:
  workflow_dispatch:
    inputs:
      titleCustom:
        description: The input Dispatch
        type: string
        required: true
        default: "Hiii"
      selectCustom:
        description: Some description
        type: choice
        required: true
        options:
          - Value 1
          - Value 2
          - Value 3
          - Value 4
        default: "Value 2"
 
      checkCustom:
        description: Checkboxx
        type: boolean
        required: false

jobs:
  job_number_one:
    runs-on: ubuntu-latest
    steps:
      - name: ECHO title
        run: | 
          echo "Title: ${{ inputs.titleCustom }}"
          echo "Title: ${{ inputs.selectCustom }}"
          echo "Title: ${{ inputs.checkCustom }}"