name: C Shell Test
on: [push]

jobs:
  run-first-command:
    runs-on: 
      ubuntu-latest
    steps:
      - name: Display some text
        run: echo "Hello, World! from second workflow!"
      - name: Display some second text
        run: |
          echo "Hello, from second workflow !!!!!!"
          echo "Hello, from second workflow !!!!!kasdhkjasd!"